### ISSUE TITLE
Slurm requirements

### ISSUE THREAD

**Issue by radaniba** [cgat-developers/ruffus#106]
Hello ruffus users

Is there any recommendation for running a ruffus pipeline on SLURM rather than SGE ?

Will the drmaa run out of the box regardless of the cluster type ?

I am testing some examples from ruffus and they are returning this error

```
drmaa.errors.DrmCommunicationException: code 2: unable to send message to qmaster using port 6444
```

Which is usually an error related to SGE as far as I know

Anyone with insights ?

Thanks

**Comment by AndreasHeger** [comment]
Hi, we have an extension to ruffus called cgatcore that is SLURM compatible, please see here:

https://github.com/cgat-developers/cgat-core

cgatcore takes care of speaking to different clusters.
