### ISSUE TITLE
Investigate if tests could be run in pytest

### ISSUE THREAD

**Issue by AndreasHeger** [cgat-developers/ruffus#86]
... might not be possible due to global pipeline dict

**Comment by jbarlow83** [comment]
The https://github.com/pytest-dev/pytest-forked plugin might help. It runs every test in a unique fork.

**Comment by QuLogic** [comment]
You could also add an autouse fixture that clears the global dict after ever test.

**Comment by AndreasHeger** [comment]
Thanks, @jbarlow83 and @QuLogic , not sure either works. I tried `--forked` but I think the issue is that pipelines in these tests are defined on import and I don't see a why around thus other than to run pytest itself multiple times.

**Comment by AndreasHeger** [comment]
This would work using the oo interface, but not the decorator pipelines. As
I understand the pipeline is constructed at import.

**Comment by AndreasHeger** [comment]
Using make to run pytests in parallel.
